# Generated by Django 2.0.2 on 2018-02-28 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('desc', models.TextField()),
                ('cost', models.IntegerField()),
                ('need_malt', models.IntegerField()),
                ('need_hops', models.IntegerField()),
                ('need_yeast', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_name', models.CharField(max_length=32)),
                ('ressources_malt', models.IntegerField(default=0)),
                ('ressources_hops', models.IntegerField(default=0)),
                ('ressources_yeast', models.IntegerField(default=0)),
                ('ressources_money', models.IntegerField(default=0)),
                ('farm_malt', models.IntegerField(default=0)),
                ('farm_hops', models.IntegerField(default=0)),
                ('farm_yeast', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileBeer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_beer', models.IntegerField()),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.Beer')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='beers',
            field=models.ManyToManyField(through='Game.ProfileBeer', to='Game.Beer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
