# Generated by Django 2.0.2 on 2018-04-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_auto_20180328_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebeer',
            name='nb_beer',
            field=models.IntegerField(default=0),
        ),
    ]
